### ISSUE TITLE
Incorrect journal abbreviations

### ISSUE THREAD

**Issue by yongrenjie** [GaurangTandon/CitationHelperForSE#1]
_Tetrahedron Letters_ should be abbreviated as _Tetrahedron Lett._ (period included)

Sample doi: 10.1016/S0040-4039(00)75204-X

> For ACS style references, the proper abbreviations may be checked against http://cassi.cas.org, as described in [Chpt 14 of the ACS Style Guide](https://doi.org/10.1021/bk-2006-STYG.ch014):

>> The journal name is an essential component of a periodical reference citation. Abbreviate the name according to the _Chemical Abstracts Service Source Index_ (_CASSI_), and italicize it. One-word journal names are not abbreviated (e.g., _Biochemistry_, _Macromolecules_, _Nature_, _Science_). No punctuation is added to end this field; thus, a period will be there with an abbreviation but not with a spelled-out word.

**Comment by GaurangTandon** [comment]
This had been fixed in a previous commit. I am closing the issue for now. If you come across more wrong journal abbreviations, please add a comment here and i'll manually fix them. Thanks!
