### ISSUE TITLE
Insert error when something goes wrong.

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/CitationHelperForSE#13]
The current behaviour of the script is to not do anything if anything goes wrong; at least that is my impression. I suggest to at least print an error where the citation should go as a visual indicator. It happened to me that I clicked the button multiple times, before I decided to open up the Error console.
I think the following standard behaviour would give enough visual feedback to the end-user to understand the script is working, but the input is not:

- short:  
   insert `<!-- Citation lookup unsuccessful -->`
- long:  
   insert citation marker, and in reference list the above.
   ```
   item<sup>\[1\]</sup>
   ### References:
   
   1.  <!-- Citation lookup unsuccessful -->
   ```

----

Add-on issue: Insert a blank line before `### References:`; this should ensure that you are outside of a list environment; otherwise nested lists will be produced.

**Comment by GaurangTandon** [comment]
Nice idea, this has been implemented, please review!
