### ISSUE TITLE
Missing Page number (Phys Rev)

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/CitationHelperForSE#18]
Example: `10.1103/PhysRevD.97.123524`

Output (long):  
`1. Diez-tejedor, A.; Flores, F.; Niz, G. Horndeski dark matter and beyond. *Phys. Rev. D* **2018,** *97* (12) [DOI: 10.1103/PhysRevD.97.123524](https://doi.org/10.1103/PhysRevD.97.123524).`

Output (short):  
`[*Phys. Rev. D* **2018,** *97* (12)](https://doi.org/10.1103/PhysRevD.97.123524)`

Should be (long):  
`1. Diez-tejedor, A.; Flores, F.; Niz, G. Horndeski dark matter and beyond. *Phys. Rev. D* **2018,** *97* (12), 123524. [DOI: 10.1103/PhysRevD.97.123524](https://doi.org/10.1103/PhysRevD.97.123524).`

Should be (short):
`[*Phys. Rev. D* **2018,** *97* (12), 123524.](https://doi.org/10.1103/PhysRevD.97.123524)`

Also tested:
```
10.1103/PhysRevX.8.031075 (not working)
https://doi.org/10.1103/RevModPhys.46.545 (working)
10.1103/PhysRevApplied.10.034044 (not working)
```

**Comment by polyluxus** [comment]
Maybe it would be a good idea to raise this issue with the CrossRef API.

**Comment by GaurangTandon** [comment]
I just noticed and it seems that these papers are missing a page number and instead have an article-number property. The article number for the given example paper is indeed `123524`.

Is it the case that some articles have page numbers and others have article numbers attached to them?

**Comment by yongrenjie** [comment]
Perhaps the most important publisher that does this is Science: see e.g. https://doi.org/10.1126/science.aax7083 However, in this case, the CrossRef API returns "eaax7083" as the page number, so the formatted reference is correct:

`[*Science* **2019,** *364* (6440), eaax7083](https://doi.org/10.1126/science.aax7083)`

The ACS Style Guide mentions what to do in the case of article numbers: 

> Some publications use article numbering, rather than page numbering, where each article starts on page 1. Use the article number in the pagination field.
> Brosset, C. _Ark. Kemi, Mineral. Geol._ **1945,** _20A,_ No. 7.

So, it seems that the correct way to treat the Phys Rev papers is to use No. XXX.

**Comment by GaurangTandon** [comment]
Thanks for fixing this, and sorry for my lack of activity on this issue!
