### ISSUE TITLE
J Chem Phys abbrev

### ISSUE THREAD

**Issue by yongrenjie** [GaurangTandon/CitationHelperForSE#22]
... is not recognised: e.g. https://doi.org/10.1063/1.1700901 produces

> [*The Journal of Chemical Physics* **1960,** *32* (1), 205–209](https://doi.org/10.1063/1.1700901)

It should be *J. Chem. Phys.*

**Comment by GaurangTandon** [comment]
Hello! As you can see in the [API response](https://api.crossref.org/works/10.1063/1.1700901), the `"short-container-title"` is `"The Journal of Chemical Physics"` resulting in the output we are seeing right now. Unfortunately, Crossref receives their data from the publisher so there's not much we can do from their side. 

Would you want me to hardcode the transformation `"The Journal of Chemical Physics"` to `"J. Chem. Phys."`? Is the former always represented as the latter?

**Comment by yongrenjie** [comment]
Sorry about the delayed response. I'm not sure what else can be done apart from hardcoding it.

In this script of mine https://github.com/yongrenjie/qcnmr-tools/blob/master/doi2biblatex.py I hardcoded some abbreviations in, J Chem Phys being one of them. So it seems that I've had this problem before with J Chem Phys and the Crossref API.

**Comment by GaurangTandon** [comment]
Thanks, alright then. I'll hardcode it.
