### ISSUE TITLE
Long format needs to respect punctuation of title 

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/CitationHelperForSE#6]
Example doi:  
10.1021/ja00178a014

Output:  
`1. Magnusson, E. Hypercoordinate molecules of second-row elements: d functions or d orbitals?. *J. Am. Chem. Soc.* **1990,** *112* (22), 7940–7951. [DOI: 10.1021/ja00178a014](https://doi.org/10.1021/ja00178a014).`

There is an extra full-stop after the question mark. So maybe it'd be best to check if the title ends with a punctuation mark and only insert a full-stop when there's none. (Btw.: This is also present in the example in #5)

**Comment by GaurangTandon** [comment]
Thanks for the report, I attempted a fix in the dev branch latest v0.2.2. Please let me know if that fixes the issue, so I can merge. Thanks!

**Comment by polyluxus** [comment]
In current testing with 0.3.0 it worked fine.

(There are enumeration issues #12, capitalisation issues #5, else it works fine)

Test set:
- 10.1021/ja00178a014  
- https://doi.org/10.1021/cr200137a
- https://onlinelibrary.wiley.com/doi/abs/10.1002/qua.10751
- https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.22885
- https://doi.org/10.1016/j.jff.2018.07.016
